# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Nicklas Hansen'
tagline:          'Machine Learning Enthusiast'
description:      'Graduate student at Machine Learning Enthusiast'
url:              https://nicklashansen.github.io
baseurl:          /

author:
  name:           'Nicklas Hansen'
  url:            https://nicklashansen.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicklashansen/nicklashansen.github.io
