# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Nicklas Hansen'
tagline:          'Machine Learning Researcher'
description:      'Machine Learning Researcher'
url:              https://nicklashansen.github.io
baseurl:          /

author:
  name:           'Nicklas Hansen'
  url:            https://nicklashansen.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicklashansen/nicklashansen.github.io
